# Lesson 5: Vacation planning using CSV files

In this lesson you'll learn to read in and work with data stored in CSV format. Data of this type looks like a table with rows and columns, and is referred to by programmers as **structured data**.

As always, begin by loading the helper functions you'll use:

In [1]:
# Imports
from helper_functions import get_llm_response, print_llm_response, display_table
from IPython.display import Markdown
import csv

Note that `import csv` here is new. Don't worry about the details for now, but this line of code will be used later to read in CSV data. You'll learn more about this code in Course 4.

## Loading data from a CSV file

You'll use the file ```itinerary.csv```, which has information about arrival and departure dates for each destination in a trip around the world.

Here is the code to load the file - the first part is the same as you've been using up to this point:

In [2]:
f = open("itinerary.csv", 'r')

The next part, where you read the data in from the file, is different because you are now reading in a CSV file:

In [3]:
csv_reader = csv.DictReader(f)
itinerary = []
for row in csv_reader:
    print(row)
    itinerary.append(row)

{'Arrival': 'July-01', 'Departure': 'July-08', 'City': 'New York', 'Country': 'USA'}
{'Arrival': 'July-09', 'Departure': 'July-16', 'City': 'Rio de Janeiro', 'Country': 'Brazil'}
{'Arrival': 'July-17', 'Departure': 'July-24', 'City': 'Cape Town', 'Country': 'South Africa'}
{'Arrival': 'July-25', 'Departure': 'August-01', 'City': 'Istanbul', 'Country': 'Turkey'}
{'Arrival': 'August-02', 'Departure': 'August-09', 'City': 'Paris', 'Country': 'France'}
{'Arrival': 'August-10', 'Departure': 'August-17', 'City': 'Tokyo', 'Country': 'Japan'}
{'Arrival': 'August-18', 'Departure': 'August-25', 'City': 'Sydney', 'Country': 'Australia'}

Now close the file:

In [4]:
f.close()

You can print the itinerary to view it's content and use the `type` function to check the datatype:

In [5]:
print(itinerary)

[{'Arrival': 'July-01', 'Departure': 'July-08', 'City': 'New York', 'Country': 'USA'}, {'Arrival': 'July-09', 'Departure': 'July-16', 'City': 'Rio de Janeiro', 'Country': 'Brazil'}, {'Arrival': 'July-17', 'Departure': 'July-24', 'City': 'Cape Town', 'Country': 'South Africa'}, {'Arrival': 'July-25', 'Departure': 'August-01', 'City': 'Istanbul', 'Country': 'Turkey'}, {'Arrival': 'August-02', 'Departure': 'August-09', 'City': 'Paris', 'Country': 'France'}, {'Arrival': 'August-10', 'Departure': 'August-17', 'City': 'Tokyo', 'Country': 'Japan'}, {'Arrival': 'August-18', 'Departure': 'August-25', 'City': 'Sydney', 'Country': 'Australia'}]

In [6]:
type(itinerary)

list

Now take a look at the first item
* Remember the first item in a list has index 0

In [7]:
# Print item 0 
print(itinerary[0])

{'Arrival': 'July-01', 'Departure': 'July-08', 'City': 'New York', 'Country': 'USA'}

This is a dictionary. You can access a particular value by passing in the key - let's look at the `Country` value in the first row of the itinerary:

In [8]:
print(itinerary[0]["Country"])

USA

## Try for yourself!

Pause the video and explore other rows in the itinerary list, or individual items in any destination. Modify the code below to explore this world tour!

In [9]:
print(itinerary[0])
print(itinerary[0]["Country"])

{'Arrival': 'July-01', 'Departure': 'July-08', 'City': 'New York', 'Country': 'USA'}
USA

<p style="background-color:#F5C780; padding:15px"> 🤖 <b>Use the Chatbot</b>:
    <br><br>
    Explain this code line by line:
    <br><br>f = open("itinerary.csv", 'r')
    <br>csv_reader = csv.DictReader(f)
    <br>itinerary = []
    <br>for row in csv_reader:
    <br>itinerary.append(row)
    <br><br>f.close()
</p>

## Structured Data

Let's visualize this itinerary in a more readable way.

* Use the ```display_table``` helper function:

In [10]:
display_table(itinerary)

Next, write code to filter the table based on some criterion - in this case if the country is Japan - and then add the information for that stop to a new list called `filtered_data`:

In [11]:
# Create an empty list to store the filtered data
filtered_data = []

# Filter by country
for trip_stop in itinerary:
    # For example: get the destinations located in "Japan"
    if trip_stop["Country"] == "Japan":
        filtered_data.append(trip_stop)

In [12]:
display_table(filtered_data)

Note that the `filtered_data` variable only contains one row.

## Using AI to suggest trip activities

Retrieve the first destination and then ask an LLM for suggestions of activities to do in that location during the dates of the visit:

In [13]:
# Select the first destination from the itinerary list (Hint: index=0)
trip_stop = itinerary[0]
print(trip_stop)

{'Arrival': 'July-01', 'Departure': 'July-08', 'City': 'New York', 'Country': 'USA'}

Create variables to store all the individual items from ```trip_stop```:

In [14]:
city = trip_stop["City"]
country = trip_stop["Country"]
arrival = trip_stop["Arrival"]
departure = trip_stop["Departure"]

Write a prompt to get activity suggestions for your trip destination:

In [15]:
prompt = f"""I will visit {city}, {country}, from {arrival} to {departure}. 
Please create a detailed daily itinerary."""

print(prompt)

I will visit New York, USA, from July-01 to July-08.
Please create a detailed daily itinerary.

Use Markdown to display the LLM response nicely in the Jupyter notebook:

In [16]:
# Store the LLM response
response = get_llm_response(prompt)

# Print in Markdown format
display(Markdown(response))

Here is a detailed daily itinerary for your New York trip from July 1 to July 8:

**July 1 (Monday): Arrival & Midtown Manhattan**
- Arrive and check into your hotel
- Afternoon: Times Square, Rockefeller Center (Top of the Rock)
- Evening: Broadway show (book tickets in advance)

**July 2 (Tuesday): Central Park & Museums**
- Morning: Central Park (Bethesda Terrace, Bow Bridge, Strawberry Fields)
- Late morning: The Metropolitan Museum of Art
- Afternoon: American Museum of Natural History
- Evening: Dinner on the Upper West Side

**July 3 (Wednesday): Statue of Liberty & Financial District**
- Morning: Statue of Liberty & Ellis Island tour (book tickets early)
- Afternoon: Wall Street, 9/11 Memorial & Museum
- Evening: Walk across Brooklyn Bridge, dinner in DUMBO

**July 4 (Thursday): Independence Day & Midtown**
- Morning: Visit the Museum of Modern Art (MoMA)
- Afternoon: Shopping on Fifth Avenue
- Evening: Watch the July 4 fireworks (locations: East River, Brooklyn Bridge Park)

**July 5 (Friday): High Line & Chelsea**
- Morning: Walk the High Line park
- Late morning: Chelsea Market for lunch
- Afternoon: Explore Greenwich Village and Washington Square Park
- Evening: Jazz club or comedy show in the Village

**July 6 (Saturday): Museums & Upper East Side**
- Morning: Guggenheim Museum
- Afternoon: Explore the Upper East Side boutiques and cafes
- Evening: Dinner at a rooftop restaurant with city views

**July 7 (Sunday): Explore Brooklyn**
- Morning: Brooklyn Botanic Garden and Prospect Park
- Afternoon: Brooklyn Museum
- Evening: Sunset at Brooklyn Heights Promenade

**July 8 (Monday): Departure**
- Morning: Last-minute shopping or visit a local café
- Check out and travel to airport

Let me know if you want restaurant or transport suggestions.

## Extra Practice

In these exercises, you'll create an itinerary for another stop on the trip! 

### Exercise 1

First, create a filtered dataset for Brazil. You'll need to update the `if` statement to select the right country.

In [23]:
# Create an empty list to store the filtered data
filtered_data = []

# Filter by country
for trip_stop in itinerary:
    # For example: get the destinations located in "Brazil"
    # Complete code on next line:
    if trip_stop["Country"] == "Brazil":
        filtered_data.append(trip_stop)

print(filtered_data)

[{'Arrival': 'July-09', 'Departure': 'July-16', 'City': 'Rio de Janeiro', 'Country': 'Brazil'}]

### Exercise 2

Next, update the variables to pass in the prompt to the LLM. You'll need to modify the code on the next line to select the first item from `filtered_data` rather than the whole `itinerary`.

In [24]:
filtered_data = itinerary[0]

city = filtered_data["City"]
country = filtered_data["Country"]
arrival = filtered_data["Arrival"]
departure = filtered_data["Departure"]

print(f" The city is: {city}")
print(f" The country is: {country}")
print(" The arrival date is: {arrival}")
print(" The departure date is: {departure}")

 The city is: New York
 The country is: USA
 The arrival date is: {arrival}
 The departure date is: {departure}

Now, you can run the prompt to get a new itinerary!

In [19]:
prompt = f"""I will visit {city}, {country}, from {arrival} to {departure}. 
Please create a detailed daily itinerary."""

print_llm_response(prompt)

Here is a detailed daily itinerary for your New York trip from July 1 to July 8:

**July 1 (Monday): Arrival & Midtown Manhattan**
- Arrive and check into your hotel
- Afternoon: Times Square, Rockefeller Center (Top of the Rock)
- Evening: Broadway show (book tickets in advance)

**July 2 (Tuesday): Central Park & Museums**
- Morning: Central Park (Bethesda Terrace, Bow Bridge, Strawberry Fields)
- Late morning: The Metropolitan Museum of Art
- Afternoon: American Museum of Natural History
- Evening: Dinner on the Upper West Side

**July 3 (Wednesday): Statue of Liberty & Financial District**
- Morning: Statue of Liberty & Ellis Island tour (book tickets early)
- Afternoon: Wall Street, 9/11 Memorial & Museum
- Evening: Walk across Brooklyn Bridge, dinner in DUMBO

**July 4 (Thursday): Independence Day & Fireworks**
- Morning: Explore Greenwich Village and SoHo
- Afternoon: Visit the High Line and Chelsea Market
- Evening: Watch July 4th fireworks (best spots: Brooklyn Bridge Park or East River Park)

**July 5 (Friday): Museums & Shopping**
- Morning: Museum of Modern Art (MoMA)
- Afternoon: Fifth Avenue shopping (Saks, Apple Store, etc.)
- Evening: Explore Hell’s Kitchen for dinner and nightlife

**July 6 (Saturday): Harlem & Upper Manhattan**
- Morning: Harlem tour (Apollo Theater, local brunch)
- Afternoon: The Cloisters (Medieval art museum in Fort Tryon Park)
- Evening: Jazz club in Harlem

**July 7 (Sunday): Explore Lower East Side & Chinatown**
- Morning: Tenement Museum
- Afternoon: Chinatown and Little Italy food tour
- Evening: Walk along the East River at sunset (East River Esplanade)

**July 8 (Monday): Departure**
- Morning: Last-minute shopping or visit a local café
- Check out and head to the airport

Let me know if you want restaurant or transport recommendations!

### Challenge exercise!

Complete the code below so that it will **print out the country of every destination** in the `itinerary.csv` file. Ask the chatbot for help if you need it!

In [28]:
f = open("itinerary.csv", "r")
csv_reader = csv.DictReader(f)
itinerary = []
for row in csv_reader:
    print(row)
    itinerary.append(row)
f.close()

# Complete the next two lines to print the country:
for trip_stop in itinerary:
    print(trip_stop["Country"])

{'Arrival': 'July-01', 'Departure': 'July-08', 'City': 'New York', 'Country': 'USA'}
{'Arrival': 'July-09', 'Departure': 'July-16', 'City': 'Rio de Janeiro', 'Country': 'Brazil'}
{'Arrival': 'July-17', 'Departure': 'July-24', 'City': 'Cape Town', 'Country': 'South Africa'}
{'Arrival': 'July-25', 'Departure': 'August-01', 'City': 'Istanbul', 'Country': 'Turkey'}
{'Arrival': 'August-02', 'Departure': 'August-09', 'City': 'Paris', 'Country': 'France'}
{'Arrival': 'August-10', 'Departure': 'August-17', 'City': 'Tokyo', 'Country': 'Japan'}
{'Arrival': 'August-18', 'Departure': 'August-25', 'City': 'Sydney', 'Country': 'Australia'}
USA
Brazil
South Africa
Turkey
France
Japan
Australia